08/10/2017 21:47:20|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:43:23|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:43:34|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
08/10/2017 22:43:37|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:44:12|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:44:27|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 220, in list_subtitles\n    query=query, season=season, episode=episode, tag=os.path.basename(video.name))\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 175, in query\n    response = checked(self.server.SearchSubtitles(self.token, criteria))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
08/10/2017 22:44:43|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:15|ERROR|Provider u'opensubtitles' terminated unexpectedly|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 79, in __delitem__\n    self.initialized_providers[name].terminate()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 145, in terminate\n    self.server.close()\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
08/10/2017 22:45:17|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:27|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
08/10/2017 22:45:30|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:30|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1331, in single_request\n    response.msg,\nProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 520 Origin Error>'|
08/10/2017 22:45:35|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:36|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1331, in single_request\n    response.msg,\nProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 520 Origin Error>'|
08/10/2017 22:45:39|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:42|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1331, in single_request\n    response.msg,\nProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Not Available>'|
08/10/2017 22:45:47|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:47|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1331, in single_request\n    response.msg,\nProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Not Available>'|
08/10/2017 22:45:52|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
08/10/2017 22:45:53|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1331, in single_request\n    response.msg,\nProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Not Available>'|
09/10/2017 10:23:33|INFO|Scanning video u'11.22.63.s01e02.720p.bluray.x264-mayhem.mkv' in u'\\\\serveur\\media\\Series TV\\11.22.63\\Season 1'|
09/10/2017 10:23:34|INFO|Downloading best subtitles for <Episode [u'11 22 63', 1x2]>|
09/10/2017 10:23:34|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:34|INFO|Initializing provider addic7ed|
09/10/2017 10:23:34|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:35|INFO|Discarding provider addic7ed|
09/10/2017 10:23:35|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:35|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:35|INFO|Logging in|
09/10/2017 10:23:36|INFO|Searching subtitles [{'moviebytesize': '2343147159', 'sublanguageid': u'eng', 'moviehash': 'bcf66eab03373bd6'}, {'sublanguageid': u'eng', 'tag': u'11.22.63.s01e02.720p.bluray.x264-mayhem.mkv'}, {'query': u'11 22 63', 'sublanguageid': u'eng', 'episode': 2, 'season': 1}]|
09/10/2017 10:23:36|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:23:36|INFO|Initializing provider podnapisi|
09/10/2017 10:23:36|INFO|Searching subtitles {'sK': u'11 22 63', 'sTE': 2, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:23:38|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:23:38|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:23:38|INFO|Initializing provider thesubdb|
09/10/2017 10:23:38|INFO|Searching subtitles {'action': 'search', 'hash': '7ac600f00433cbc65de7e2c368cd22e5'}|
09/10/2017 10:23:38|INFO|Downloaded 0 subtitle(s)|
09/10/2017 10:23:38|INFO|Terminating provider thesubdb|
09/10/2017 10:23:38|INFO|Terminating provider opensubtitles|
09/10/2017 10:23:38|INFO|Logging out|
09/10/2017 10:23:40|INFO|Terminating provider addic7ed|
09/10/2017 10:23:40|INFO|Terminating provider podnapisi|
09/10/2017 10:23:40|INFO|Scanning video u'11.22.63.s01e04.720p.bluray.x264-mayhem.mkv' in u'\\\\serveur\\media\\Series TV\\11.22.63\\Season 1'|
09/10/2017 10:23:41|INFO|Downloading best subtitles for <Episode [u'11 22 63', 1x4]>|
09/10/2017 10:23:41|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:41|INFO|Initializing provider addic7ed|
09/10/2017 10:23:41|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:41|INFO|Discarding provider addic7ed|
09/10/2017 10:23:41|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:41|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:41|INFO|Logging in|
09/10/2017 10:23:41|INFO|Searching subtitles [{'moviebytesize': '2344453160', 'sublanguageid': u'eng', 'moviehash': '39067de748eceaf6'}, {'sublanguageid': u'eng', 'tag': u'11.22.63.s01e04.720p.bluray.x264-mayhem.mkv'}, {'query': u'11 22 63', 'sublanguageid': u'eng', 'episode': 4, 'season': 1}]|
09/10/2017 10:23:42|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:23:42|INFO|Initializing provider podnapisi|
09/10/2017 10:23:42|INFO|Searching subtitles {'sK': u'11 22 63', 'sTE': 4, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:23:43|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:23:43|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:23:43|INFO|Initializing provider thesubdb|
09/10/2017 10:23:43|INFO|Searching subtitles {'action': 'search', 'hash': 'f4ca4253bea7ef0275d7af2c7acf175d'}|
09/10/2017 10:23:43|INFO|Downloaded 0 subtitle(s)|
09/10/2017 10:23:43|INFO|Terminating provider thesubdb|
09/10/2017 10:23:43|INFO|Terminating provider opensubtitles|
09/10/2017 10:23:43|INFO|Logging out|
09/10/2017 10:23:44|INFO|Terminating provider addic7ed|
09/10/2017 10:23:44|INFO|Terminating provider podnapisi|
09/10/2017 10:23:44|INFO|Scanning video u'11.22.63.s01e05.720p.bluray.x264-mayhem.mkv' in u'\\\\serveur\\media\\Series TV\\11.22.63\\Season 1'|
09/10/2017 10:23:45|INFO|Downloading best subtitles for <Episode [u'11 22 63', 1x5]>|
09/10/2017 10:23:45|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:45|INFO|Initializing provider addic7ed|
09/10/2017 10:23:45|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:45|INFO|Discarding provider addic7ed|
09/10/2017 10:23:45|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:45|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:45|INFO|Logging in|
09/10/2017 10:23:45|INFO|Searching subtitles [{'moviebytesize': '2343208816', 'sublanguageid': u'eng', 'moviehash': '3904e1351d09acb3'}, {'sublanguageid': u'eng', 'tag': u'11.22.63.s01e05.720p.bluray.x264-mayhem.mkv'}, {'query': u'11 22 63', 'sublanguageid': u'eng', 'episode': 5, 'season': 1}]|
09/10/2017 10:23:46|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:23:46|INFO|Initializing provider podnapisi|
09/10/2017 10:23:46|INFO|Searching subtitles {'sK': u'11 22 63', 'sTE': 5, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:23:47|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:23:47|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:23:47|INFO|Initializing provider thesubdb|
09/10/2017 10:23:47|INFO|Searching subtitles {'action': 'search', 'hash': '9e7f4ee7f8ae8691aa639013dd6cf41e'}|
09/10/2017 10:23:47|INFO|Downloaded 0 subtitle(s)|
09/10/2017 10:23:47|INFO|Terminating provider thesubdb|
09/10/2017 10:23:47|INFO|Terminating provider opensubtitles|
09/10/2017 10:23:47|INFO|Logging out|
09/10/2017 10:23:48|INFO|Terminating provider addic7ed|
09/10/2017 10:23:48|INFO|Terminating provider podnapisi|
09/10/2017 10:23:48|INFO|Scanning video u'11.22.63.s01e06.720p.bluray.x264-mayhem.mkv' in u'\\\\serveur\\media\\Series TV\\11.22.63\\Season 1'|
09/10/2017 10:23:50|INFO|Downloading best subtitles for <Episode [u'11 22 63', 1x6]>|
09/10/2017 10:23:50|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:50|INFO|Initializing provider addic7ed|
09/10/2017 10:23:50|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:50|INFO|Discarding provider addic7ed|
09/10/2017 10:23:50|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:50|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:50|INFO|Logging in|
09/10/2017 10:23:50|INFO|Searching subtitles [{'moviebytesize': '2343181274', 'sublanguageid': u'eng', 'moviehash': '085c16b09fc930ff'}, {'sublanguageid': u'eng', 'tag': u'11.22.63.s01e06.720p.bluray.x264-mayhem.mkv'}, {'query': u'11 22 63', 'sublanguageid': u'eng', 'episode': 6, 'season': 1}]|
09/10/2017 10:23:50|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:23:51|INFO|Initializing provider podnapisi|
09/10/2017 10:23:51|INFO|Searching subtitles {'sK': u'11 22 63', 'sTE': 6, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:23:52|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:23:52|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:23:52|INFO|Initializing provider thesubdb|
09/10/2017 10:23:52|INFO|Searching subtitles {'action': 'search', 'hash': '8beefcd685913494ed9a8f3d18fa6732'}|
09/10/2017 10:23:52|INFO|Downloaded 0 subtitle(s)|
09/10/2017 10:23:52|INFO|Terminating provider thesubdb|
09/10/2017 10:23:52|INFO|Terminating provider opensubtitles|
09/10/2017 10:23:52|INFO|Logging out|
09/10/2017 10:23:53|INFO|Terminating provider addic7ed|
09/10/2017 10:23:53|INFO|Terminating provider podnapisi|
09/10/2017 10:23:53|INFO|Scanning video u'11.22.63.s01e08.720p.bluray.x264-mayhem.mkv' in u'\\\\serveur\\media\\Series TV\\11.22.63\\Season 1'|
09/10/2017 10:23:55|INFO|Downloading best subtitles for <Episode [u'11 22 63', 1x8]>|
09/10/2017 10:23:55|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:55|INFO|Initializing provider addic7ed|
09/10/2017 10:23:55|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:55|INFO|Discarding provider addic7ed|
09/10/2017 10:23:55|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:55|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:55|INFO|Logging in|
09/10/2017 10:23:55|INFO|Searching subtitles [{'moviebytesize': '2839067828', 'sublanguageid': u'eng', 'moviehash': '4acb09a95288f7f4'}, {'sublanguageid': u'eng', 'tag': u'11.22.63.s01e08.720p.bluray.x264-mayhem.mkv'}, {'query': u'11 22 63', 'sublanguageid': u'eng', 'episode': 8, 'season': 1}]|
09/10/2017 10:23:55|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:23:55|INFO|Initializing provider podnapisi|
09/10/2017 10:23:55|INFO|Searching subtitles {'sK': u'11 22 63', 'sTE': 8, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:23:57|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:23:57|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:23:57|INFO|Initializing provider thesubdb|
09/10/2017 10:23:57|INFO|Searching subtitles {'action': 'search', 'hash': 'cbac247b34dc56cc270b30e5cc1c2966'}|
09/10/2017 10:23:57|INFO|Downloaded 0 subtitle(s)|
09/10/2017 10:23:57|INFO|Terminating provider thesubdb|
09/10/2017 10:23:57|INFO|Terminating provider opensubtitles|
09/10/2017 10:23:57|INFO|Logging out|
09/10/2017 10:23:58|INFO|Terminating provider addic7ed|
09/10/2017 10:23:58|INFO|Terminating provider podnapisi|
09/10/2017 10:23:58|INFO|Scanning video u'Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.mkv' in u'\\\\serveur\\media\\Series TV\\Ozark\\Season 1'|
09/10/2017 10:23:59|INFO|Downloading best subtitles for <Episode [u'Ozark', 1x2]>|
09/10/2017 10:23:59|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:23:59|INFO|Initializing provider addic7ed|
09/10/2017 10:23:59|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:23:59|INFO|Discarding provider addic7ed|
09/10/2017 10:23:59|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:23:59|INFO|Initializing provider opensubtitles|
09/10/2017 10:23:59|INFO|Logging in|
09/10/2017 10:23:59|INFO|Searching subtitles [{'moviebytesize': '1048422729', 'sublanguageid': u'eng', 'moviehash': 'adf5c816e20bd935'}, {'sublanguageid': u'eng', 'tag': u'Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.mkv'}, {'query': u'Ozark', 'sublanguageid': u'eng', 'episode': 2, 'season': 1}]|
09/10/2017 10:24:00|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:24:00|INFO|Initializing provider podnapisi|
09/10/2017 10:24:00|INFO|Searching subtitles {'sK': u'Ozark', 'sTE': 2, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:24:01|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:24:01|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:24:01|INFO|Initializing provider thesubdb|
09/10/2017 10:24:01|INFO|Searching subtitles {'action': 'search', 'hash': 'af81b9ee79a13145a6ade5cfd1ee1e6b'}|
09/10/2017 10:24:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955625962' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:01|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:24:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955626766' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'resolution'])|
09/10/2017 10:24:02|INFO|Computing score of <OpenSubtitlesSubtitle '1955626154' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:24:02|INFO|Computing score of <OpenSubtitlesSubtitle '1955631569' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec'])|
09/10/2017 10:24:02|INFO|Computing score of <OpenSubtitlesSubtitle '1955625961' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:24:02|INFO|Computing score of <OpenSubtitlesSubtitle '1955626159' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:24:02|INFO|Computing score of <OpenSubtitlesSubtitle '1955626765' [en]> for video <Episode [u'Ozark', 1x2]> with {'hearing_impaired': u'False'}|
09/10/2017 10:24:02|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'resolution'])|
09/10/2017 10:24:02|INFO|Downloading subtitle <OpenSubtitlesSubtitle '1955625962' [en]>|
09/10/2017 10:24:02|INFO|Downloading subtitle <OpenSubtitlesSubtitle '1955625962' [en]>|
09/10/2017 10:24:03|INFO|Downloaded 1 subtitle(s)|
09/10/2017 10:24:03|INFO|Terminating provider thesubdb|
09/10/2017 10:24:03|INFO|Terminating provider opensubtitles|
09/10/2017 10:24:03|INFO|Logging out|
09/10/2017 10:24:03|INFO|Terminating provider addic7ed|
09/10/2017 10:24:03|INFO|Terminating provider podnapisi|
09/10/2017 10:24:03|INFO|Saving <OpenSubtitlesSubtitle '1955625962' [en]> to u'\\\\serveur\\media\\Series TV\\Ozark\\Season 1\\Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.en.srt'|
09/10/2017 10:26:57|INFO|Scanning video 'Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.mkv' in '\\\\serveur\\media\\Series TV\\Ozark\\Season 1'|
09/10/2017 10:26:57|INFO|Downloading best subtitles for <Episode ['Ozark', 1x2]>|
09/10/2017 10:26:57|INFO|Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])|
09/10/2017 10:26:57|INFO|Initializing provider addic7ed|
09/10/2017 10:26:58|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 10:26:58|INFO|Discarding provider addic7ed|
09/10/2017 10:26:58|INFO|Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])|
09/10/2017 10:26:58|INFO|Initializing provider opensubtitles|
09/10/2017 10:26:58|INFO|Logging in|
09/10/2017 10:26:58|INFO|Searching subtitles [{'moviebytesize': '1048422729', 'sublanguageid': u'eng', 'moviehash': 'adf5c816e20bd935'}, {'sublanguageid': u'eng', 'tag': 'Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.mkv'}, {'query': 'Ozark', 'sublanguageid': u'eng', 'episode': 2, 'season': 1}]|
09/10/2017 10:26:59|INFO|Listing subtitles with provider u'podnapisi' and languages set([<Language [en]>])|
09/10/2017 10:26:59|INFO|Initializing provider podnapisi|
09/10/2017 10:26:59|INFO|Searching subtitles {'sK': 'Ozark', 'sTE': 2, 'sXML': 1, 'sTS': 1, 'sL': 'en'}|
09/10/2017 10:27:00|INFO|Skipping provider u'subscenter': no language to search for|
09/10/2017 10:27:00|INFO|Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])|
09/10/2017 10:27:00|INFO|Initializing provider thesubdb|
09/10/2017 10:27:00|INFO|Searching subtitles {'action': 'search', 'hash': 'af81b9ee79a13145a6ade5cfd1ee1e6b'}|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955625962' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955626766' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'resolution'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955626154' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955631569' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955625961' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955626159' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 341 with final matches set(['episode', 'format', 'series', 'year', 'season', 'video_codec', 'resolution'])|
09/10/2017 10:27:01|INFO|Computing score of <OpenSubtitlesSubtitle '1955626765' [en]> for video <Episode ['Ozark', 1x2]> with {'hearing_impaired': 'False'}|
09/10/2017 10:27:01|INFO|Computed score 339 with final matches set(['episode', 'format', 'series', 'year', 'season', 'resolution'])|
09/10/2017 10:27:01|INFO|Downloading subtitle <OpenSubtitlesSubtitle '1955625962' [en]>|
09/10/2017 10:27:01|INFO|Downloading subtitle <OpenSubtitlesSubtitle '1955625962' [en]>|
09/10/2017 10:27:01|INFO|Downloaded 1 subtitle(s)|
09/10/2017 10:27:01|INFO|Terminating provider thesubdb|
09/10/2017 10:27:01|INFO|Terminating provider opensubtitles|
09/10/2017 10:27:01|INFO|Logging out|
09/10/2017 10:27:02|INFO|Terminating provider addic7ed|
09/10/2017 10:27:02|INFO|Terminating provider podnapisi|
09/10/2017 10:27:02|INFO|Saving <OpenSubtitlesSubtitle '1955625962' [en]> to '\\\\serveur\\media\\Series TV\\Ozark\\Season 1\\Ozark.S01E02.MULTi.720P.WEBRip.NF.x264-LiBERTAD.en.srt'|
09/10/2017 16:15:13|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 16:27:57|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 21:13:48|ERROR|Provider u'opensubtitles' terminated unexpectedly|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 79, in __delitem__\n    self.initialized_providers[name].terminate()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 145, in terminate\n    self.server.close()\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
09/10/2017 21:18:37|ERROR|Unexpected error in provider u'opensubtitles'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 68, in __getitem__\n    provider.initialize()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 138, in initialize\n    \'subliminal v%s\' % __short_version__))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
09/10/2017 21:21:40|ERROR|Unexpected error in provider u'addic7ed'|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 118, in list_subtitles_provider\n    return self[provider].list_subtitles(video, provider_languages)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 273, in list_subtitles\n    return [s for s in self.query(video.series, video.season, video.year)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 228, in query\n    show_id = self.get_show_id(series, year, country)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\addic7ed.py", line 201, in get_show_id\n    show_ids = self._get_show_ids()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 1231, in decorate\n    should_cache_fn)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 833, in get_or_create\n    async_creator) as value:\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 154, in __enter__\n    return self._enter()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\lock.py", line 87, in _enter\n    value = value_fn()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\region.py", line 788, in get_value\n    value = self.backend.get(key)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 220, in get\n    with self._dbm_file(False) as dbm:\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 212, in _dbm_file\n    with self._use_rw_lock(write):\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 207, in _use_rw_lock\n    with self._rw_lock.read():\n  File "C:\\Python27\\lib\\contextlib.py", line 17, in __enter__\n    return self.gen.next()\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 327, in read\n    self.acquire_read_lock(True)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 408, in acquire_read_lock\n    return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\util\\langhelpers.py", line 66, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n  File "C:\\Python27\\lib\\site-packages\\dogpile\\cache\\backends\\file.py", line 400, in _module\n    import fcntl\nImportError: No module named fcntl'|
09/10/2017 21:22:11|ERROR|Unexpected error in provider 'opensubtitles', discarding it|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 171, in download_subtitle\n    self[subtitle.provider_name].download_subtitle(subtitle)\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 224, in download_subtitle\n    response = checked(self.server.DownloadSubtitles(self.token, [str(subtitle.subtitle_id)]))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
09/10/2017 21:22:11|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:11|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:11|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:11|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:12|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:12|WARNING|Provider 'opensubtitles' is discarded|
09/10/2017 21:22:22|ERROR|Provider u'opensubtitles' terminated unexpectedly|'Traceback (most recent call last):\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\core.py", line 79, in __delitem__\n    self.initialized_providers[name].terminate()\n  File "C:\\Python27\\lib\\site-packages\\subliminal\\providers\\opensubtitles.py", line 144, in terminate\n    checked(self.server.LogOut(self.token))\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1243, in __call__\n    return self.__send(self.__name, args)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1602, in __request\n    verbose=self.__verbose\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1283, in request\n    return self.single_request(host, handler, request_body, verbose)\n  File "C:\\Python27\\lib\\xmlrpclib.py", line 1313, in single_request\n    response = h.getresponse(buffering=True)\n  File "C:\\Python27\\lib\\httplib.py", line 1121, in getresponse\n    response.begin()\n  File "C:\\Python27\\lib\\httplib.py", line 438, in begin\n    version, status, reason = self._read_status()\n  File "C:\\Python27\\lib\\httplib.py", line 394, in _read_status\n    line = self.fp.readline(_MAXLINE + 1)\n  File "C:\\Python27\\lib\\socket.py", line 480, in readline\n    data = self._sock.recv(self._rbufsize)\n  File "C:\\Python27\\lib\\ssl.py", line 766, in recv\n    return self.read(buflen)\n  File "C:\\Python27\\lib\\ssl.py", line 653, in read\n    v = self._sslobj.read(len)\nSSLError: (\'The read operation timed out\',)'|
